node:
  build: ./node
  links:
    - logstash

logstash:
  image: logstash:latest
  command: logstash -e 'input { tcp { port => 5000 } } output { elasticsearch { hosts => ["elasticsearch:9200"] } }'
  ports:
    - "5000:5000"
  links:
    - elasticsearch

elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"

kibana:
  image: kibana:latest
  ports:
    - "5601:5601"
  links:
    - elasticsearch
