node:
  build: ./node
  ports:
    - "3000:3000"
  # links:
  #   - logstash

# logstash:
#   image: logstash:latest
#   command: logstash -e 'input { stdin{} } output { elasticsearch { hosts => ["elasticsearch:9200"] } }' #'input { tcp { port => 5000 } } output { elasticsearch { hosts => ["elasticsearch:9200"] } }'
#   tty: true
#   stdin_open: true
#   # volumes:
#     # - ./logstash/config:/etc/logstash/conf.d
#   ports:
#     - "5000:5000"
#   links:
#     - elasticsearch
#
# elasticsearch:
#   image: elasticsearch:latest
#   command: elasticsearch -Des.network.host=0.0.0.0
#   ports:
#     - "9200:9200"
#     - "9300:9300"
#
# kibana:
#   image: kibana:latest
#   #volumes:
#   #  - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
#   ports:
#     - "5601:5601"
#   links:
#     - elasticsearch
